### PR TITLE
add --cached option for git rm

### PR DESCRIPTION
**Pull request by cloorc**
For newer git release, command `git rm` will remove files definitely and it's not possible to add them back again by command `git add`. In this scenario, option `--cache` should be added to command `git rm` to prevent from physically dropping.

The only change I want to merge to `apache/maven-scm` is the `--cache` option not the `pom.xml`. Thanks a lot.

### CODE REVIEW

**Comment by michael-o** [comment]
Your PR needs several updates:

* You have changed the artifactId
* Added a custom repo
* The option in wrong, it is `--cached`

The docs from the API say "remove from the SCM". `--cached` does not do that.

**Comment by michael-o** [comment]
Still waiting for updates...

**Comment by cloorc** [comment]
Hi @michael-o , you are right. And I've already updated my PR. I thought scm should only remove paths from the index instead of removing these files definitely, which would result in file lost. Thanks for your patient.

**Comment by cloorc** [comment]
Just leave me a chance to keep the files this plugin is going to remove. It was a long period since the last time I posted this PR. Without this chance, you may lost these files before you confirm it. BTW, it's could be a small change that many developers do not care, how about just close this PR? That's it.

**Comment by michael-o** [comment]
I did not intend to close, but merely wanted to point out that if you really need it, a command param is the way to go. There is a sample commit you can build on if you like.

**Pull request closed without merging**
