### PR TITLE
[SCM-941] remove bogus method

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by rfscholte** [comment]
The path is quite an important element, why not fix  the assert and unittests?

**Comment by elharo** [comment]
Given that this code tries to account for differences between Unix and Windows paths, I'm not sure that's doable until the Windows machines in Jenkins get fixed.

**Comment by rfscholte** [comment]
Windows nodes are fixed, right?

**Comment by elharo** [comment]
seem to be but now several of the Linux nodes are failing :-(

**Pull request closed without merging**
