### PR TITLE
Fix for SCM-695 : Mvn release plugin problems with too many - in name

### PR DESCRIPTION
**Pull request by sporniket**
This is the squashed commits see #27

### CODE REVIEW

**Comment by sporniket** [comment]
Hello, I rebased my pull request

**Comment by sporniket** [comment]
This pull request is getting old and I didn't get any feedback about it. Just in case I was not giving enough description : 

This is a fix for [SCM-695] (http://jira.codehaus.org/browse/SCM-695). It contains the fix and the test suite.

It allows to fix [MRELEASE-701] (https://jira.codehaus.org/browse/MRELEASE-701) (succesfully tested the release:prepare using the fixed scm plugin)

The principle of this fix is to test that the relative path to the submodule pom point to a file (File.exists), since the relative path is computed by simply removing the path of the parent project folder from the path of the submodule pom, if appliable.

The test suite has been modified to create a temporary folder containing all the folders and poms required to pass the test. A new test has been added to test a flat project with submodule folder names prefixed by the parent folder name. This test, and the folder/file creation, has been written to be OS independant (esp. the temp file creation), but I do not have a computer with Windows, so I couldn't test on this OS.

**Comment by tomaswolf** [comment]
Wouldn't simply
```
final String canonicalWorkingDirectory = workingDirectory.getCanonicalPath() + File.separator;
```
also fix this?

**Comment by sporniket** [comment]
I guess it would work. I have no time to test that for now.

**Comment by michael-o** [comment]
Can someone please rebase and drop unaffected changes even if they are correct? We also need a proper IT which reproduces the issue.

**Comment by jira-importer** [comment]
Resolve #908

**Pull request closed without merging**
