### PR TITLE
SCM-988 NOT a Pull request, Testing only

### PR DESCRIPTION
**Pull request by nielsbasjes**
The best way to test if these https://github.com/apache/maven-gh-actions-shared/pull/44 changes work is to try them.

### CODE REVIEW

**Comment by nielsbasjes** [comment]
Apparently not allowed

**Comment by mthmulders** [comment]
@michael-o M.E.R.G.I.N.G. this one, too? ;-)

**Comment by michael-o** [comment]
> @michael-o M.E.R.G.I.N.G. this one, too? ;-)

Y.E.S., P.L.E.A.S.E.!

**Comment by nielsbasjes** [comment]
Having both under my own name already ran the test I wanted.
Just installing mercurial makes the build ~18 seconds longer for macOS.

**Comment by jira-importer** [comment]
Resolve #1215

**Pull request closed without merging**
