### PR TITLE
[SCM-969] Remove all deprecated providers

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by michael-o** [comment]
`grep` tells me some changes is till missing

**Comment by michael-o** [comment]
@cstamas Looks much better now. A few issues left:
```
./maven-scm-api/src/main/java/org/apache/maven/scm/provider/ScmProviderRepository.java:     * <li>IBM Rational ClearQuest Enabled UCM ClearCase (task)
./maven-scm-api/src/main/java/org/apache/maven/scm/provider/ScmProviderRepository.java:     * like Perforce and Clearcase where the server must track where a
./maven-scm-api/src/main/java/org/apache/maven/scm/provider/ScmProviderRepository.java:     * user checks out to.  If false, the server entry (clientspec in Perforce
./maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AbstractScmMojo.java:     * The user name (used by svn, starteam and perforce protocol).
./maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AbstractScmMojo.java:     * The user password (used by svn, starteam and perforce protocol).
./maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AbstractScmMojo.java:     * A workItem for SCMs like RTC, TFS etc, that may require additional
```

Please have a look, those as specific code spots for those SCMs. I want to nuke them to oblivion. WDYT?

**Review by cstamas — APPROVED** [review]

**Comment by michael-o** [comment]
@cstamas What about the remaining spots. I'd like o nuke them too.

**Comment by cstamas** [comment]
@michael-o 
re maven-scm-api: I'd deprecate them (IIUC these are specific for some removed providers?), to not complicate lives if somebody takes dropped provider to maintain it by themselves. And after several release cycles we can see: too drop it or not.
re maven-scm-plugin: in 2 of 3 SVN is mentioned, that is left in place, no? So, I'd apply same as above: deprecate and sit and wait.

**Comment by michael-o** [comment]
@cstamas Right, I will deprecate everything which is used by providers we don't support anymore.

**Comment by jira-importer** [comment]
Resolve #1193

**Pull request merged**
