### PR TITLE
[SCM-807] Improve test for ScmManager.add(...)

### PR DESCRIPTION
**Pull request by kwin**
check returned file paths
fix SVN returning path with leading spaces

### CODE REVIEW

**Comment by kwin** [comment]
@michael-o Should the ScmFile path always have forward slashes? Currently mercurial uses backward slashes on Windows (at least for add(...)).

**Comment by michael-o** [comment]
I would consider that `ScmFile` is oriented towards the current OS/FS, totally SCM-agnostic. It is upto the provider to normalize to the SCM. It seems it is not documented. Subversion, like Mercurial, uses FS-dependent separators.

**Comment by kwin** [comment]
But `CheckInScmResult` always returns `ScmFile` with forward slashes (even on Mercurial and Subversion)

**Comment by michael-o** [comment]
> But `CheckInScmResult` always returns `ScmFile` with forward slashes (even on Mercurial and Subversion)

Well, the we need to define the behavior for 2.0.0 and apply it in Maven Release as well. It is up to us.

**Comment by michael-o** [comment]
I'd say lets make it consistent: Create a JIRA issue which shall document in JAvadoc that system-agnostic forward slashes need to be passed and will be returned, align all callers and returners for that.

**Comment by kwin** [comment]
Sounds, good. I created https://issues.apache.org/jira/browse/SCM-998 to track that and will make the test in this PR more lenient for the time being.

**Comment by jira-importer** [comment]
Resolve #1037

**Pull request closed without merging**
