### PR TITLE
Updated Jazz: StatusConsumer and fixed CommitCommand

### PR DESCRIPTION
**Pull request by benze**
Provided way to reset JazzStatusConsumer state machine
Ignore stderr output if successful associate command

### CODE REVIEW

**Comment by michael-o** [comment]
Can you rebase and explain the purpose of your change?

**Comment by benze** [comment]
@michael-o Frankly I don't remember precisely what this was about, but something about the output not being structured in an easily consumable way for multiple changesets.  I haven't used Jazz in 3 years now so I don't even have a platform to run it against and try it out.  But I do remember it was a blocker at the time for me.

**Comment by michael-o** [comment]
Thanks for getting back. Do you think it is still worthwhile? Unless someone can really look over and retest, I don't see a chance to properly merge it.

**Comment by benze** [comment]
I remember working with @ChrisGWarp on this and we had merged some changes into the Jazz connector, but they were kind of dependent on this change in the release plugin.  At the time I remember him saying that it was going to be a while before the changesets would be picked up by the release plugin.

At the time I had to build a custom these plugin to get the Jazz connector to work, and make sure that the build prices used the custom plugin until a new release/scm plugin was released. 

I would hate to see this work wasted, but unless someone has access to a jazz platform I don't even know how to test it.  I can't imagine it breaking anything, but you know software...

**Comment by michael-o** [comment]
> I would hate to see this work wasted, but unless someone has access to a jazz platform I don't even know how to test it.

Me too, but it is virtually impossible to maintain code you cannot test itself. Team Concert being non-ree puts us in a position to rely on slow dripping commits.

**Comment by michael-o** [comment]
Alright, I will just wait. Thank you!

**Pull request closed without merging**
