### PR TITLE
[MNG-6829] Replace trimmed StringUtils#isEmpty(String) and #isNotEmpy

### PR DESCRIPTION
**Pull request by timtebeek**
Additional replacements as compared to https://github.com/apache/maven-scm/pull/169, now also replacing where the input was trimmed.

@elharo would you mind having look at this one and a few to follow? I want to start this up again. :)

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by olamy** [comment]
shouldn't we have a corresponding SCM- issue rather than MNG- as it's not a core change?

**Comment by slachiewicz** [comment]
We agreed that it's not cost effective to write tools to create Jira per project with this automation

**Comment by olamy** [comment]
> We agreed that it's not cost effective to write tools to create Jira per project with this automation

Fine. but where is this agreement? Do you know if something was talked about it on a mailing list?

**Comment by timtebeek** [comment]
Hi @olamy ; Thanks for voicing your concern with regards to consistently tagging issues with an appropriate Jira ticket as per the project. It's a valid concern, and it's come up before; I'll link to a few earlier discussions here.

- https://github.com/apache/maven-scm/pull/183#issuecomment-1685231834
- https://issues.apache.org/jira/browse/MNG-6825?focusedCommentId=17707546&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17707546
- https://issues.apache.org/jira/browse/MNG-6825?focusedCommentId=17707549&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17707549

I'll give a bit more context about these changes here, as I don't think we've met before. I work on OpenRewrite, which allows folks to make safe automated code changes. Together with the Moderne platform, that allows me to apply changes broadly with ease. I'm using these two tools to for instance work on

- https://issues.apache.org/jira/browse/MNG-6825
  reduce dependencies on plexus-utils/maven-shared-utils/commons-lang3/commons-io
- https://issues.apache.org/jira/browse/MNG-6829
  Remove commons-lang3 dependency
- https://issues.apache.org/jira/browse/MNG-6847
  Explicit type can be replaced by the diamond operator

There's a few others I'd like to tackle in the future with automated changes, such as for instance
- https://issues.apache.org/jira/browse/MNG-7077
  the PlexusTestCase as a parent class should be transformed into a proper junit 5 extension

All of these are small individual changes, that have often been applied to a subset of projects already, some by hand, some with tooling support. But given that there's some ~90 Apache Maven repositories, you'll find projects in various states.

What I hope to do is lift all projects up to a common consistent state, such that they are all easier to maintain going forward. As per an earlier request I'm pushing frequent small PRs such that they are easier to review & troubleshoot if ever needed. That does mean a lot of PRs will be created, especially when replacing individual Plexus/Shared/Commons utilities methods.

The parts that are automated right now are making the code changes, and creating PRs through the Moderne platform, both of which already existed before this effort. There's no easy way to hook in Jira issue creation right now, and for a lot of these changes an issue per project would only amount to as much as the PRs title & body already contain. That's why in the earlier discussions we'd arrived at using a common issue across projects for reference, such that they are all linked back to a single effort across many projects.

Does that help put the above changes into context? And would you then agree with us continuing in the manner?

**Comment by olamy** [comment]
@timtebeek I'm definitely fine with doing so for such trivial changes BUT this need to be agreed/recorded somewhere on a mailing list so nobody will get back on this complaining about the lack of Jira for this. 
Having it on release notes could be great though (if possible)

**Comment by elharo** [comment]
@timtebeek Just assign me as a reviewer on any PR you want me to look at. Otherwise I'm likely to miss them. Of course, it's 100% fine if someone else reviews and merges these first.

**Comment by timtebeek** [comment]
Thanks all! I'll resume creating PRs, create issues for new overarching themes, and use my best judgement when a change grows beyond trivial for a particular project.

**Pull request merged**
