### PR TITLE
Change: Added consumeProcessOutput() to stop hang.

### PR DESCRIPTION
**Pull request by ChrisGWarp**
This is a simple fix to stop the build from hanging when executing "svn --version".

### CODE REVIEW

**Comment by jieryn** [comment]
You make it difficult for observers to review your changes when you completely change the encoding or line endings or whatever you're doing that fully replaces the file. :-(

**Comment by ChrisGWarp** [comment]
I did not know that I'd knowingly did that. Did I miss something in the git setup?

**Comment by jieryn** [comment]
I'm not sure what the root cause is, perhaps see if this makes sense:

https://help.github.com/articles/dealing-with-line-endings/

**Comment by ChrisGWarp** [comment]
I've now forced:

C:\Documents and Settings\admin\workspace\maven-scm>git config --global
--list
user.name=Chris Graham
user.email=ChrisGWarp@gmail.com
core.autocrlf=true

which is what it recommended. Which is what I thought that it was anyway.
Shrug.

The files are otherwise probably the same.

**Comment by jieryn** [comment]
Cool, can you update the pull request with the new commit after re-adding (thereby forcing your settings) and committing?

**Pull request merged**
