### PR TITLE
fix git remove command for filename start with '-'

### PR DESCRIPTION
**Pull request by sunnyqeen**
add command has it but not remove command

### CODE REVIEW

**Comment by sunnyqeen** [comment]
could this PR be merged to 1.x ?

**Comment by michael-o** [comment]
You may want to review all other commands to pass this consistently for the future.

**Comment by michael-o** [comment]
Also create a JIRA issue for this. I will assign to me and process as soon as all questions have been resolved.

**Comment by sunnyqeen** [comment]
could you create the Jira for me? I am not the jira user.
And I just got the bug by this command. checked other commands, look fine.

**Comment by michael-o** [comment]
Will create the JIRA issue.

**Comment by michael-o** [comment]
> could this PR be merged to 1.x ?

Yes, but don't expect a release anytime soon.

**Pull request closed without merging**
