### PR TITLE
[SCM-930] Update a few deps/plugins and remove some trailing spaces / formatting in poms

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@olamy I think you will want to drop java 6 support on travis.  If I recall this build is java 7+ at this point and it's failing due to the clean plugin at the very least.  I did try to move it back a few ubuntu releases on travis and got all but java 6 running.

**Comment by hazendaz** [comment]
@eolivelli Great that makes sense.  I had turned on travis on my end for this today.  For now I'll just remove the jdk 6 run since that is invalid at this point in time.

**Comment by eolivelli** [comment]
Btw thank you for your contribution

Please create a JIRA and put the id at the beginning of the commit message.

This is a guide that helps understanding our workflow

https://maven.apache.org/guides/development/guide-helping.html

**Comment by hazendaz** [comment]
@eolivelli Thanks.  I've created the ticket and added it on the PR.  If squashed during merge that should be enough.  If you need me to do this on each commit, let me know and I'll rebase this as well as cleanup a few of the commits around travis ci.  Thanks.

**Comment by michael-o** [comment]
I will look through this later.

**Comment by rfscholte** [comment]
I think you're pointing to Karl Heinz his scripts that auto generate issues for every change. Personally I don't mind having all plugin updates in one issue.
It doesn't effect the resulting artifacts, so since issues are also the release notes, it doesn't add that much.

**Comment by hazendaz** [comment]
Either way I'm fine.  I'll start by splitting out travis fix portion and submit a separate PR with that then rebase this one.  Slf4j is pretty benign as I don't think that specific module changes much but I do agree if the core is on 1.7.25, then this too should stay on that.  Probably bigger concern for me here from my point of view is why groovy was so old.  I see that one is for the MKS (PTC Integrety) only.  I'm not sure if outside of the build that matters much but their newer apis don't work from what I tested.  I do have access to MKS to test though if need be (although we long stopped using it for source management).

**Comment by hazendaz** [comment]
One other note.  I do generally in nearly all cases keep dependencies separate.  PR never matters much to me nor jira behind the scenes in that regard.  The separate commit I've always found more powerful as it is easier to revert an issue which is more important.  But again I can do this all separately.  No issue there :)

**Comment by hazendaz** [comment]
see #95 For travis only fix.  I'll rebase once that one makes it's way in.

**Comment by hazendaz** [comment]
closing.

**Comment by jira-importer** [comment]
Resolve #1155

**Pull request closed without merging**
