### PR TITLE
[SCM-925] Implement RemoveCommand in maven-scm-provider-jgit with TCK test for all providers

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
@michael-o Any idea why the HG provider fails for the remove test? I have no experience with HG at all.

**Comment by michael-o** [comment]
No idea, I have other problems with Mercurial as well. Run master w/o your patch and see whether `tck-hg` passes for you. Not for me.

**Comment by kwin** [comment]
`mvn clean verify -Prun-its` runs fine for me on `maven-scm-provider-hg`, however I removed the remove test from that provider as that failure is not related to SCM-925. Maybe someone else can look into that.

**Comment by michael-o** [comment]
For me it fails from master:
```
[ERROR] Failures:
[ERROR]   HgDiffCommandTckTest.testDiffCommand:94->ScmTckTestCase.addToWorkingTree:241 Expected 1 file in the added files list [] expected:<1> but was:<0>
[ERROR]   HgStatusCommandTckTest>StatusCommandTckTest.testStatusCommand:107->ScmTckTestCase.addToWorkingTree:241 Expected 1 file in the added files list [] expected:<1> but was:<0>
[ERROR]   HgUpdateCommandTckTest>UpdateCommandTckTest.testUpdateCommand:119->ScmTckTestCase.addToWorkingTree:241 Expected 1 file in the added files list [] expected:<1> but was:<0>
[INFO]
[ERROR] Tests run: 18, Failures: 3, Errors: 0, Skipped: 0
```
on
``´
mosipov@bsd1srv:/usr/home/mosipov/var/Projekte/maven-scm (master =)
$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven-3.6.3
Java version: 1.8.0_332, vendor: OpenJDK BSD Porting Team, runtime: /usr/local/openjdk8/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "freebsd", version: "12.3-stable", arch: "amd64", family: "unix"
mosipov@bsd1srv:/usr/home/mosipov/var/Projekte/maven-scm (master =)
$ hg --version
Mercurial Distributed SCM (version 6.1.4)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2022 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jira-importer** [comment]
Resolve #1150

**Pull request merged**
