### PR TITLE
[SCM-775] support workItem/Tasks for scm deliver operations

### PR DESCRIPTION
**Pull request by ChrisGWarp**
This pull requests implements the SCM-775 functionality needed to support workItem/Tasks for scm deliver operations. Currently implemented for Jazz, the base work applied, will allow TFS, ClearCase and others to access work items.

There is also a corresponding patch attached to MRELEASE-909.

All feedback welcome.

### CODE REVIEW

**Comment by rafaelodon** [comment]
I'm really interested in this pull-request. Not being able to associate workItem is definetely a huge obstacle to the maven release plugin in my current project.

**Comment by michael-o** [comment]
Please create a JIRA issue, a test would be great.

**Comment by michael-o** [comment]
Please rebase and squash.

**Comment by michael-o** [comment]
Any chance to rebase and squash?

**Comment by ChrisGWarp** [comment]
I thought I’d committed that.

Let me review where I’m st with it. I had to pull it in from SVN days...

**Comment by michael-o** [comment]
OK, great. Just rebase and we'll look at together.

**Comment by michael-o** [comment]
This provider has been removed in master.

**Pull request closed without merging**
